import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  const customLoader = ({ src }: { src: string }) => src
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/icon?family=Material+Icons'
        ></link>
      </Head>
      <nav className='topBar'>
        <div className='wrap'>
          <h1>
            <a href='#' className='logo'>
              WOWOROOM
            </a>
          </h1>
          <span className='material-icons menuToggle'>menu</span>
          <ul className='topBar-menu'>
            <li>
              <a href='#bedAdvantage'>床墊優勢</a>
            </li>
            <li>
              <a href='#recommendation'>好評推薦</a>
            </li>
            <li>
              <a href='#transport'>運送方式</a>
            </li>
            <li>
              <a href='#orderInfo'>立即預訂</a>
            </li>
          </ul>
        </div>
      </nav>

      <section className='wrap' id='bedAdvantage'>
        <div className='banner'>
          <h2 className='banner-text'>
            窩窩家居
            <br />
            跟您一起品味生活
          </h2>
        </div>
        <h3 className='section-title'>床墊優勢</h3>
        <ul className='bedAdvantage'>
          <li>
            <Image
              width={350}
              height={140}
              className='bedAdvantage-img'
              src='https://i.imgur.com/tR426y5.png'
              alt='原木料環保'
              loader={customLoader}
            />
            <p className='bedAdvantage-text'>原木料環保</p>
          </li>
          <li>
            <Image
              width={350}
              height={350}
              loader={customLoader}
              className='bedAdvantage-img'
              src='https://i.imgur.com/Fd2MiBb.png'
              alt='好收納'
            />
            <p className='bedAdvantage-text'>好收納</p>
          </li>
          <li>
            <Image
              width={350}
              height={140}
              loader={customLoader}
              className='bedAdvantage-img'
              src='https://github.com/hexschool/js-training/blob/main/%E7%AC%AC%E4%B9%9D%E9%80%B1%E4%B8%BB%E7%B7%9A%E4%BB%BB%E5%8B%99%E5%9C%96%E5%BA%AB/5n1uTFh.png?raw=true'
              alt='好組裝'
            />
            <p className='bedAdvantage-text'>好組裝</p>
          </li>
        </ul>
      </section>

      <section className='recommendation' id='recommendation'>
        <div className='wrap'>
          <h3 className='section-title'>好評推薦</h3>
          <div className='recommendation-wall'>
            <ul className='gallery-top'>
              <li className='recommendation-card'>
                <Image
                  width={96}
                  height={96}
                  loader={customLoader}
                  src='https://i.imgur.com/cXcOLhu.png'
                  alt=''
                />
                <div className='recommend-content'>
                  <div className='recommend-img'>
                    <Image
                      width={40}
                      height={40}
                      loader={customLoader}
                      src='https://i.imgur.com/I9L7WOr.png'
                      alt=''
                    />
                    <div>
                      <p>王六角</p>
                      <p className='recommend-text'>Jodan 雙人床架</p>
                    </div>
                  </div>
                  <p>CP值很高。</p>
                </div>
              </li>
              <li className='recommendation-card'>
                <Image
                  width={96}
                  height={96}
                  loader={customLoader}
                  src='https://i.imgur.com/BefHmH2.png'
                  alt=''
                />
                <div className='recommend-content'>
                  <div className='recommend-img'>
                    <Image
                      width={40}
                      height={40}
                      loader={customLoader}
                      src='https://i.imgur.com/CUFGfay.png'
                      alt=''
                    />
                    <div>
                      <p>Leaf</p>
                      <p className='recommend-text'>Antony 雙人床架</p>
                    </div>
                  </div>
                  <p>很喜歡～還有送三年保固～</p>
                </div>
              </li>
              <li className='recommendation-card'>
                <Image
                  width={96}
                  height={96}
                  loader={customLoader}
                  src='https://github.com/hexschool/js-training/blob/main/%E7%AC%AC%E4%B9%9D%E9%80%B1%E4%B8%BB%E7%B7%9A%E4%BB%BB%E5%8B%99%E5%9C%96%E5%BA%AB/3IATkJG.png?raw=true'
                  alt=''
                />
                <div className='recommend-content'>
                  <div className='recommend-img'>
                    <Image
                      width={40}
                      height={40}
                      loader={customLoader}
                      src='https://i.imgur.com/8WwZsLS.png'
                      alt=''
                    />
                    <div>
                      <p>美濃鄧子琪</p>
                      <p className='recommend-text'>Charles 系列儲物組合</p>
                    </div>
                  </div>
                  <p>廚房必備美用品！</p>
                </div>
              </li>
              <li className='recommendation-card'>
                <Image
                  width={96}
                  height={96}
                  loader={customLoader}
                  src='https://i.imgur.com/HvT3zlU.png'
                  alt=''
                />
                <div className='recommend-content'>
                  <div className='recommend-img'>
                    <Image
                      width={40}
                      height={40}
                      loader={customLoader}
                      src='https://i.imgur.com/NycuPVy.png'
                      alt=''
                    />
                    <div>
                      <p>isRaynotArray</p>
                      <p className='recommend-text'>Antony 雙人床架</p>
                    </div>
                  </div>
                  <p>物超所值!</p>
                </div>
              </li>
              <li className='recommendation-card'>
                <Image
                  width={96}
                  height={96}
                  loader={customLoader}
                  src='https://i.imgur.com/Ed7bxLr.png'
                  alt=''
                />
                <div className='recommend-content'>
                  <div className='recommend-img'>
                    <Image
                      width={40}
                      height={40}
                      loader={customLoader}
                      src='https://i.imgur.com/zdFOQIv.png'
                      alt=''
                    />
                    <div>
                      <p>程鮭魚</p>
                      <p className='recommend-text'>Louvre 雙人床架</p>
                    </div>
                  </div>
                  <p>租屋用剛剛好</p>
                </div>
              </li>
            </ul>
            <ul className='gallery-bottom'>
              <li className='recommendation-card'>
                <Image
                  width={96}
                  height={96}
                  loader={customLoader}
                  src='https://i.imgur.com/BefHmH2.png'
                  alt=''
                />
                <div className='recommend-content'>
                  <div className='recommend-img'>
                    <Image
                      width={40}
                      height={40}
                      loader={customLoader}
                      src='https://i.imgur.com/W7fyzp2.png'
                      alt=''
                    />
                    <div>
                      <p>小杰</p>
                      <p className='recommend-text'>Louvre 雙人床架</p>
                    </div>
                  </div>
                  <p>非常舒適，有需要會再回購</p>
                </div>
              </li>
              <li className='recommendation-card'>
                <Image
                  width={96}
                  height={96}
                  loader={customLoader}
                  src='https://i.imgur.com/mjA01Tk.png'
                  alt=''
                />
                <div className='recommend-content'>
                  <div className='recommend-img'>
                    <Image
                      width={40}
                      height={40}
                      loader={customLoader}
                      src='https://github.com/hexschool/js-training/blob/main/%E7%AC%AC%E4%B9%9D%E9%80%B1%E4%B8%BB%E7%B7%9A%E4%BB%BB%E5%8B%99%E5%9C%96%E5%BA%AB/8O1cOnG.png?raw=true'
                      alt=''
                    />
                    <div>
                      <p>江八角</p>
                      <p className='recommend-text'>Charles 雙人床架</p>
                    </div>
                  </div>
                  <p>品質不錯～</p>
                </div>
              </li>
              <li className='recommendation-card'>
                <Image
                  width={96}
                  height={96}
                  loader={customLoader}
                  src='https://i.imgur.com/npA3DgP.png'
                  alt=''
                />
                <div className='recommend-content'>
                  <div className='recommend-img'>
                    <Image
                      width={40}
                      height={40}
                      loader={customLoader}
                      src='https://i.imgur.com/C0NDvSA.png'
                      alt=''
                    />
                    <div>
                      <p>juni讚神</p>
                      <p className='recommend-text'>Antony 床邊桌</p>
                    </div>
                  </div>
                  <p>讚ㄉ！</p>
                </div>
              </li>
              <li className='recommendation-card'>
                <Image
                  width={96}
                  height={96}
                  loader={customLoader}
                  src='https://i.imgur.com/Ed7bxLr.png'
                  alt=''
                />
                <div className='recommend-content'>
                  <div className='recommend-img'>
                    <Image
                      width={40}
                      height={40}
                      loader={customLoader}
                      src='https://i.imgur.com/hUsTZDm.png'
                      alt=''
                    />
                    <div>
                      <p>久安說安安</p>
                      <p className='recommend-text'>Antony 單人床架</p>
                    </div>
                  </div>
                  <p>一個躺剛剛好。</p>
                </div>
              </li>
              <li className='recommendation-card'>
                <Image
                  width={96}
                  height={96}
                  loader={customLoader}
                  src='https://i.imgur.com/mjA01Tk.png'
                  alt=''
                />
                <div className='recommend-content'>
                  <div className='recommend-img'>
                    <Image
                      width={40}
                      height={40}
                      loader={customLoader}
                      src='https://github.com/hexschool/js-training/blob/main/%E7%AC%AC%E4%B9%9D%E9%80%B1%E4%B8%BB%E7%B7%9A%E4%BB%BB%E5%8B%99%E5%9C%96%E5%BA%AB/3ako6QX.png?raw=true'
                      alt=''
                    />
                    <div>
                      <p>PeiQun</p>
                      <p className='recommend-text'>Antony 雙人床架</p>
                    </div>
                  </div>
                  <p>睡起來很舒適</p>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </section>

      <section className='transport' id='transport'>
        <h3 className='section-title'>運送方式</h3>
        <ul className='transport-intro'>
          <li className='transport-card'>
            <div className='cardImg'>
              <span className='material-icons'>shopping_cart</span>
            </div>
            <h4>STEP.1</h4>
            <p>選購商品</p>
          </li>
          <li className='transport-card'>
            <div className='cardImg'>
              <span className='material-icons'>format_list_bulleted</span>
            </div>
            <h4>STEP.2</h4>
            <p>填寫預定資料</p>
          </li>
          <li className='transport-card'>
            <div className='cardImg'>
              <span className='material-icons'>local_post_office</span>
            </div>
            <h4>STEP.3</h4>
            <p>預定成功</p>
          </li>
          <li className='transport-card'>
            <div className='cardImg'>
              <span className='material-icons'>done</span>
            </div>
            <h4>STEP.4</h4>
            <p>Email 付款資訊</p>
          </li>
        </ul>
      </section>

      <section className='wrap productDisplay'>
        <select name='' className='productSelect'>
          <option value='全部' selected>
            全部
          </option>
          <option value='床架'>床架</option>
          <option value='收納'>收納</option>
          <option value='窗簾'>窗簾</option>
        </select>
        <ul className='productWrap'>
          <li className='productCard'>
            <h4 className='productType'>新品</h4>
            <Image
              width={232.75}
              height={300}
              loader={customLoader}
              src='https://hexschool-api.s3.us-west-2.amazonaws.com/custom/dp6gW6u5hkUxxCuNi8RjbfgufygamNzdVHWb15lHZTxqZQs0gdDunQBS7F6M3MdegcQmKfLLoxHGgV3kYunUF37DNn6coPH6NqzZwRfhbsmEblpJQLqXLg4yCqUwP3IE.png'
              alt=''
            />
            <a href='#' className='addCardBtn'>
              加入購物車
            </a>
            <h3>Antony 雙人床架／雙人加大</h3>
            <del className='originPrice'>NT$18,000</del>
            <p className='nowPrice'>NT$12,000</p>
          </li>
          <li className='productCard'>
            <h4 className='productType'>新品</h4>
            <Image
              width={232.75}
              height={300}
              loader={customLoader}
              src='https://hexschool-api.s3.us-west-2.amazonaws.com/custom/B87OUPkvlBvBl7Wyv3xj9ErOazczyGO8AFM5Nll38yEUvXMJHFXnid4g9YMzJOMq6t54ucmfgO4p7xw1azkleNYyhkEIINs8zJNbCPz1JUAZwaTKqIkaVQ3mRo2VBzAH.png'
              alt=''
            />
            <a href='#' className='addCardBtn'>
              加入購物車
            </a>
            <h3>Antony 雙人床架／雙人加大</h3>
            <del className='originPrice'>NT$18,000</del>
            <p className='nowPrice'>NT$12,000</p>
          </li>
          <li className='productCard'>
            <h4 className='productType'>新品</h4>
            <Image
              width={232.75}
              height={300}
              loader={customLoader}
              src='https://hexschool-api.s3.us-west-2.amazonaws.com/custom/tTQQggBAfhl0vEeM7WmTwij1JbAwC7MBD2TSyjHbZHvBjnLU5tOtoGszOmODOEu6DRjzdjIpcEzeCCkmRWaL8JDJwaaWglER7P3V4JXKT7FT5gm0UL45CaHpSVlEXbKK.png'
              alt=''
            />
            <a href='#' className='addCardBtn'>
              加入購物車
            </a>
            <h3>Antony 雙人床架／雙人加大</h3>
            <del className='originPrice'>NT$18,000</del>
            <p className='nowPrice'>NT$12,000</p>
          </li>
          <li className='productCard'>
            <h4 className='productType'>新品</h4>
            <Image
              width={232.75}
              height={300}
              loader={customLoader}
              src='https://hexschool-api.s3.us-west-2.amazonaws.com/custom/xgI6wM3uUCpkEEcauvHs67BFjGqG6Qxa9JTfOZTys6C0yJjqw5c8nJuA31gX77YVf04kZotGP9ZFQU7hLXkuoaRwNSssScpFnzfyPzYKODuyhw2QJrT1bDSim7aOBryv.png'
              alt=''
            />
            <a href='#' className='addCardBtn'>
              加入購物車
            </a>
            <h3>Antony 雙人床架／雙人加大</h3>
            <del className='originPrice'>NT$18,000</del>
            <p className='nowPrice'>NT$12,000</p>
          </li>
          <li className='productCard'>
            <h4 className='productType'>新品</h4>
            <Image
              width={232.75}
              height={300}
              loader={customLoader}
              src='https://hexschool-api.s3.us-west-2.amazonaws.com/custom/Zr4h1Oqvc6NtAnpe5pNqJfGYyBJshAlKctfv0BTAZBqVAuvfSAWk4bcidBd8qBu1lRn5TWvib6O3UbmIAEt5w8SdB94GuFplZn6IM4SBvtxWJA2VnOqvQOsKungCPDXv.png'
              alt=''
            />
            <a href='#' className='addCardBtn'>
              加入購物車
            </a>
            <h3>Antony 雙人床架／雙人加大</h3>
            <del className='originPrice'>NT$18,000</del>
            <p className='nowPrice'>NT$12,000</p>
          </li>
          <li className='productCard'>
            <h4 className='productType'>新品</h4>
            <Image
              width={232.75}
              height={300}
              loader={customLoader}
              src='https://hexschool-api.s3.us-west-2.amazonaws.com/custom/Tx99wDepg56aO5dGH7uGpU7REZwQLd1W0ec43M6cFw3o3z4eXTbeovq8WVseZ476BntlQnPPzaqkZgoj7xITviHMqf0kiAetjxyvuLiTmr7WdulcL364MTL321qZRJkP.png'
              alt=''
            />
            <a href='#' className='addCardBtn'>
              加入購物車
            </a>
            <h3>Antony 雙人床架／雙人加大</h3>
            <del className='originPrice'>NT$18,000</del>
            <p className='nowPrice'>NT$12,000</p>
          </li>
          <li className='productCard'>
            <h4 className='productType'>新品</h4>
            <Image
              width={232.75}
              height={300}
              loader={customLoader}
              src='https://hexschool-api.s3.us-west-2.amazonaws.com/custom/VYPOpg83Jg7Ft5raI0eyzs6xSz0ttKzSJSklFq7il0HdwJ1iQ9kLHAU19rmkSapmyzRErTm1sxWO725W7CnowkRjwxgSyyRBo1ihGLwNbfYtgbo2nCTY9sarjqoxQbYX.png'
              alt=''
            />
            <a href='#' className='addCardBtn'>
              加入購物車
            </a>
            <h3>Antony 雙人床架／雙人加大</h3>
            <del className='originPrice'>NT$18,000</del>
            <p className='nowPrice'>NT$12,000</p>
          </li>
          <li className='productCard'>
            <h4 className='productType'>新品</h4>
            <Image
              width={232.75}
              height={300}
              loader={customLoader}
              src='https://hexschool-api.s3.us-west-2.amazonaws.com/custom/XWnC8Of71WeSvCbkGy5MvZSyCrim50F9njuwHypcbiimd8tWscxGdecRAyaNheboQkqQAiCWK12GwuwMBvEtAarU2Y7mKTwKZIqhIExyQzbAbls7NTOdN2vX1OAyEaAN.png'
              alt=''
            />
            <a href='#' className='addCardBtn'>
              加入購物車
            </a>
            <h3>Antony 雙人床架／雙人加大</h3>
            <del className='originPrice'>NT$18,000</del>
            <p className='nowPrice'>NT$12,000</p>
          </li>
        </ul>
      </section>

      <section className='shoppingCart'>
        <h3 className='section-title'>我的購物車</h3>
        <div className='overflowWrap'>
          <table className='shoppingCart-table'>
            <tr>
              <th>品項</th>
              <th>單價</th>
              <th>數量</th>
              <th>金額</th>
              <th></th>
            </tr>
            <tr>
              <td>
                <div className='cardItem-title'>
                  <Image
                    width={80}
                    height={80}
                    loader={customLoader}
                    src='https://i.imgur.com/HvT3zlU.png'
                    alt=''
                  />
                  <p>Antony 雙人床架／雙人加大</p>
                </div>
              </td>
              <td>NT$12,000</td>
              <td>1</td>
              <td>NT$12,000</td>
              <td className='discardBtn'>
                <a href='#' className='material-icons'>
                  clear
                </a>
              </td>
            </tr>
            <tr>
              <td>
                <a href='#' className='discardAllBtn'>
                  刪除所有品項
                </a>
              </td>
              <td></td>
              <td></td>
              <td>
                <p>總金額</p>
              </td>
              <td>NT$13,980</td>
            </tr>
          </table>
        </div>
      </section>

      <section className='orderInfo wrap' id='orderInfo'>
        <h3 className='section-title'>填寫預訂資料</h3>
        <form action='' className='orderInfo-form'>
          <div className='orderInfo-formGroup'>
            <label htmlFor='customerName' className='orderInfo-label'>
              姓名
            </label>
            <div className='orderInfo-inputWrap'>
              <input
                type='text'
                className='orderInfo-input'
                id='customerName'
                placeholder='請輸入姓名'
                name='姓名'
              />
              <p className='orderInfo-message' data-message='姓名'>
                必填
              </p>
            </div>
          </div>
          <div className='orderInfo-formGroup'>
            <label htmlFor='customerPhone' className='orderInfo-label'>
              電話
            </label>
            <div className='orderInfo-inputWrap'>
              <input
                type='tel'
                className='orderInfo-input'
                id='customerPhone'
                placeholder='請輸入電話'
                name='電話'
              />
              <p className='orderInfo-message' data-message='電話'>
                必填
              </p>
            </div>
          </div>
          <div className='orderInfo-formGroup'>
            <label htmlFor='customerEmail' className='orderInfo-label'>
              Email
            </label>
            <div className='orderInfo-inputWrap'>
              <input
                type='email'
                className='orderInfo-input'
                id='customerEmail'
                placeholder='請輸入 Email'
                name='Email'
              />
              <p className='orderInfo-message' data-message='Email'>
                必填
              </p>
            </div>
          </div>
          <div className='orderInfo-formGroup'>
            <label htmlFor='customerAddress' className='orderInfo-label'>
              寄送地址
            </label>
            <div className='orderInfo-inputWrap'>
              <input
                type='text'
                className='orderInfo-input'
                id='customerAddress'
                placeholder='請輸入寄送地址'
                name='寄送地址'
              />
              <p className='orderInfo-message' data-message='寄送地址'>
                必填
              </p>
            </div>
          </div>
          <div className='orderInfo-formGroup'>
            <label htmlFor='tradeWay' className='orderInfo-label'>
              交易方式
            </label>
            <div className='orderInfo-inputWrap'>
              <select id='tradeWay' className='orderInfo-input' name='交易方式'>
                <option value='ATM' selected>
                  ATM
                </option>
                <option value='信用卡'>信用卡</option>
                <option value='超商付款'>超商付款</option>
              </select>
            </div>
          </div>
          <input type='submit' value='送出預訂資料' className='orderInfo-btn' />
        </form>
      </section>
    </>
  )
}
